### ISSUE TITLE
Change the Management (Vorstand) in imprint

### ISSUE THREAD

**Issue by dajana** [rubyberlin/rubyberlin.org#47]
I just noticed that Thilo is still mentioned as Vorstand in the imprint. Could somebody please enter Roman Messer here: http://www.ruby.berlin/imprint 
Thanks!

**Comment by skade** [comment]
Done http://www.ruby.berlin/imprint

**Comment by myabc** [comment]
@dajana @skade  please can we change the contact number? I still, occasionally, get calls for the Verein.

**Comment by dajana** [comment]
Fine by me. You can put mine in there: +491726944443
