### ISSUE TITLE
Euruko 2015 is missing from events

### ISSUE THREAD

**Issue by skade** [rubyberlin/rubyberlin.org#49]
We provided substantial service, I think that's appropriate.

**Comment by hagenburger** [comment]
You are not talking about this one?

<img width="329" src="https://cloud.githubusercontent.com/assets/103399/13699999/5993505c-e77e-11e5-8f55-9b124d0be1b5.png">

**Comment by skade** [comment]
I'm talking about http://www.euruko2015.org/

**Comment by hagenburger** [comment]
lol, I did not was up yet ;) I’ll take care of it after work!
